/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e6",
        "surface-tint": "#506350",
        "on-secondary": "#ffffff",
        "primary-container": "#2c3e2d",
        "on-secondary-fixed": "#261900",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#594313",
        surface: "#f9f9f7",
        "inverse-surface": "#2f3130",
        "surface-bright": "#f9f9f7",
        "on-primary-fixed-variant": "#394b39",
        background: "#f9f9f7",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0e1f10",
        outline: "#747871",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1a1c1b",
        tertiary: "#1a271b",
        "surface-variant": "#e2e3e1",
        "surface-container-highest": "#e2e3e1",
        primary: "#172819",
        "on-tertiary-fixed-variant": "#3c4a3c",
        "surface-dim": "#dadad8",
        "tertiary-container": "#2f3d30",
        "secondary-fixed-dim": "#e3c286",
        "on-error": "#ffffff",
        "surface-container": "#eeeeec",
        "on-surface-variant": "#434842",
        "outline-variant": "#c3c8c0",
        "inverse-primary": "#b7ccb5",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f4f4f2",
        "secondary-container": "#fddb9d",
        "tertiary-fixed-dim": "#bbcbb8",
        "on-tertiary-fixed": "#121f13",
        "secondary-fixed": "#ffdea3",
        "error-container": "#ffdad6",
        "on-secondary-container": "#785f2c",
        "tertiary-fixed": "#d7e7d4",
        "primary-fixed-dim": "#b7ccb5",
        "inverse-on-surface": "#f1f1ef",
        "primary-fixed": "#d3e8d0",
        secondary: "#735b29",
        "on-primary-container": "#94a993",
        "on-background": "#1a1c1b",
        "on-tertiary-container": "#98a896",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        unit: "4px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["Public Sans"],
        "body-lg": ["Public Sans"],
        "label-bold": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "body-md": ["Public Sans"],
        "headline-display": ["Public Sans"],
        "label-sm": ["Public Sans"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-display": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
