// Dummy applicant records for the ADHA admin portal demo.
// Field names mirror the input shape expected by /api/assessment (see
// app/api/assessment/route.js and lib/assessment/engine.js).

export const applicants = [
  {
    id: "app-1001",
    fullName: "Fatima Al Mazrouei",
    emiratesId: "784-1988-1234567-1",
    submittedDate: "2026-06-18",
    status: "Pending Review",
    age: 34,
    dependents: 2,
    employment: "government",
    monthlyIncome: 28000,
    otherIncome: 0,
    existingMonthlyDebt: 2500,
    creditCardMinimums: 500,
    requestedLoanAmount: 1800000,
    financingRatePercent: 4.5,
    requestedTenureYears: 25,
    aecbScore: 780,
    housingSituation: "renting_adequate",
    firstTimeBeneficiary: true,
    vulnerabilityFlags: [],
  },
  {
    id: "app-1002",
    fullName: "Ahmed Al Ketbi",
    emiratesId: "784-1979-2345678-2",
    submittedDate: "2026-06-20",
    status: "Pending Review",
    age: 46,
    dependents: 5,
    employment: "private",
    monthlyIncome: 12000,
    otherIncome: 0,
    existingMonthlyDebt: 1500,
    creditCardMinimums: 300,
    requestedLoanAmount: 900000,
    financingRatePercent: 5,
    requestedTenureYears: 20,
    aecbScore: 640,
    housingSituation: "family_overcrowded",
    firstTimeBeneficiary: true,
    vulnerabilityFlags: ["single_parent", "chronic_illness"],
  },
  {
    id: "app-1003",
    fullName: "Mariam Al Suwaidi",
    emiratesId: "784-1990-3456789-3",
    submittedDate: "2026-06-22",
    status: "Pending Review",
    age: 30,
    dependents: 1,
    employment: "private",
    monthlyIncome: 18000,
    otherIncome: 2000,
    existingMonthlyDebt: 3000,
    creditCardMinimums: 800,
    requestedLoanAmount: 1200000,
    financingRatePercent: 4.75,
    requestedTenureYears: 25,
    aecbScore: 690,
    housingSituation: "family_adequate",
    firstTimeBeneficiary: false,
    vulnerabilityFlags: [],
  },
  {
    id: "app-1004",
    fullName: "Khalid Al Nuaimi",
    emiratesId: "784-1975-4567890-4",
    submittedDate: "2026-06-25",
    status: "Pending Review",
    age: 51,
    dependents: 3,
    employment: "business",
    monthlyIncome: 35000,
    otherIncome: 5000,
    existingMonthlyDebt: 9000,
    creditCardMinimums: 2000,
    requestedLoanAmount: 2500000,
    financingRatePercent: 5.25,
    requestedTenureYears: 15,
    aecbScore: 520,
    housingSituation: "owns_adequate",
    firstTimeBeneficiary: false,
    vulnerabilityFlags: [],
  },
  {
    id: "app-1005",
    fullName: "Salama Al Dhaheri",
    emiratesId: "784-1965-5678901-5",
    submittedDate: "2026-06-27",
    status: "Pending Review",
    age: 58,
    dependents: 4,
    employment: "retired",
    monthlyIncome: 9000,
    otherIncome: 1000,
    existingMonthlyDebt: 800,
    creditCardMinimums: 0,
    requestedLoanAmount: 700000,
    financingRatePercent: 5,
    requestedTenureYears: 12,
    aecbScore: 610,
    housingSituation: "inadequate_unsafe",
    firstTimeBeneficiary: true,
    vulnerabilityFlags: ["widowed", "elderly"],
  },
  {
    id: "app-1006",
    fullName: "Omar Al Shamsi",
    emiratesId: "784-1992-6789012-6",
    submittedDate: "2026-06-29",
    status: "Pending Review",
    age: 33,
    dependents: 0,
    employment: "government",
    monthlyIncome: 42000,
    otherIncome: 0,
    existingMonthlyDebt: 4000,
    creditCardMinimums: 1000,
    requestedLoanAmount: 2200000,
    financingRatePercent: 4.25,
    requestedTenureYears: 25,
    aecbScore: 820,
    housingSituation: "owns_adequate",
    firstTimeBeneficiary: false,
    vulnerabilityFlags: [],
  },
];

export const getApplicantById = (id) => applicants.find((a) => a.id === id) ?? null;
